openapi: 3.0.0
x-stoplight:
  id: 0gctwh9jjrgpu
info:
  title: ResourceBooking
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/auth/callback/{provider}/':
    parameters:
      - schema:
          type: string
        name: provider
        in: path
        required: true
    post:
      summary: retrieve jwt
      tags:
        - auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwttoken:
                    type: string
                    description: Jwt token from the server to perform futher api call
                required:
                  - jwttoken
        default:
          description: default
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/errorMsg'
      operationId: post-auth-callback
      description: Provide the code and state verification to server after oauth2 provider redirect in order to get JWT for further api call
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: string
                  description: state from the redirect
                code:
                  type: string
                  description: code return by oauth2 provider to generate the token id
                nonce:
                  type: string
                  description: 'encrypted state metadata to confirm legitimacy of the user before providing the jwt token '
              required:
                - state
                - code
                - nonce
        description: ''
  '/auth/redirect/{provider}':
    parameters:
      - schema:
          type: string
        name: provider
        in: path
        required: true
    get:
      summary: redirect
      tags:
        - auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirecturl:
                    type: string
                    description: redirect url
                  nonce:
                    type: string
                    description: nonce should persisted in the client storage before redirecting. Nonce will be check during the callback.
                required:
                  - redirecturl
                  - nonce
      operationId: get-auth-redirect
      description: get endpoint for redirect url and nonce
  '/user{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags:
        - user
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      parameters: []
      security:
        - Authorization: []
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      security:
        - Authorization: []
      tags:
        - user
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      security:
        - Authorization: []
      tags:
        - user
  '/admin/resource/{resourcename}':
    parameters:
      - schema:
          type: string
        name: resourcename
        in: path
        required: true
    delete:
      summary: Delete resource id
      tags:
        - booking
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resourceIdent'
        default:
          description: default
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/errorMsg'
      operationId: delete-resouce-resourceid
      description: Remove resource from the booking system
      security:
        - Authorization: []
  /admin/resource:
    post:
      summary: create-new-booking-resource
      tags:
        - booking
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  resourceIdent:
                    $ref: '#/components/schemas/resourceIdent'
                  createdate:
                    type: string
                    format: date-time
                    description: date the resource was created
                  modifiedate:
                    type: string
                    format: date-time
                    description: last modified date
                required:
                  - resourceIdent
                  - createdate
                  - modifiedate
        default:
          description: default
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/errorMsg'
      operationId: post-admin-resource
      description: Create new booking resource
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: name of the resource for booking
                shortname:
                  type: string
                  description: shortname of the booking
                resourcetype:
                  type: string
                  description: resource type
                longdesc:
                  type: string
                  description: long description of the resource
                imageurl:
                  type: string
                  description: url to the image
              required:
                - name
                - shortname
                - resourcetype
                - longdesc
        description: Provide name the type
      security:
        - Authorization: []
    parameters: []
  '/admin/booking/{resourcename}':
    parameters:
      - schema:
          type: string
        name: resourcename
        in: path
        required: true
    get:
      summary: get booking info
      tags:
        - booking
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/resourceSlotAdmin'
      operationId: get-admin-booking-resourcename
      description: 'endpoint to allow admin to view all the activity of all avalailble '
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  description: date will default to current if zero is provided
              required:
                - date
        description: ''
      security:
        - Authorization: []
  /booking:
    post:
      summary: Create Booking
      operationId: post-booking
      responses:
        default:
          description: default
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/errorMsg'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: Accept
              items:
                $ref: '#/components/schemas/resourceBooking'
        description: User may be able to create bookings of multiple items
      description: Create booking
      security:
        - Authorization: []
      tags:
        - booking
    parameters: []
  /booking/resources:
    get:
      summary: booking resource
      tags:
        - booking
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/resourceIdent'
      operationId: get-resources
      description: List all available resource name and type which can be booked
      security:
        - Authorization: []
    parameters: []
  '/booking/{resourccename}/{date}':
    parameters:
      - schema:
          type: string
        name: resourccename
        in: path
        required: true
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: booking information for the resource for 24 hours format
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  resourceShortname:
                    type: string
                    description: name of the resource
                  date:
                    type: string
                    format: date
                    description: date of resource booked
                  bookingSlots:
                    description: listing of all active booking and checkout session
                    type: array
                    items:
                      $ref: '#/components/schemas/resourseSlotDetail'
                required:
                  - resourceShortname
                  - date
                  - bookingSlots
          headers: {}
        default:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: '#/components/schemas/errorMsg'
      operationId: get-booking-info
      description: List 24hr booking information of a resource
      security:
        - Authorization: []
      tags:
        - booking
      parameters: []
  /booking/checkout:
    post:
      summary: Checkout All Orders
      tags:
        - booking
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  urltocheckout:
                    type: string
                    description: url to be redirected for checkout
                required:
                  - urltocheckout
      operationId: post-booking-checkout
      description: Retrieve the checkout session and prepare to be redirect
      security:
        - Authorization: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: user may multi select
              items:
                $ref: '#/components/schemas/resourseSlotDetail'
        description: slots requested for the checkout
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
    resourceIdent:
      title: resourceIdent
      x-stoplight:
        id: 75bquxhl2eqf6
      x-tags:
        - slot
      type: object
      description: Booking Resource Identity
      x-examples:
        example-1:
          id: string
          name: string
          type: string
      properties:
        id:
          type: string
          description: 'Unique identitfier for this slot, will be use as a reference to resource booking'
        shortname:
          type: string
          description: Name of resource
          maxLength: 20
        resourcetype:
          type: string
          description: 'Type of resource eg: a court, a vehicle, an equipment, a training session or consulting session'
        longdesc:
          type: string
          description: Long Description for the resource
          maxLength: 200
        imageurl:
          type: string
          format: uri
          description: image url of the images
      required:
        - id
        - shortname
        - resourcetype
        - longdesc
    resourceBooking:
      title: resourceBooking
      x-stoplight:
        id: jq7kqkyujsre5
      x-tags:
        - booking
      type: object
      description: Booking information on a daily basis starting Sunday. Each request will provide at maxiumum 7 days information of the booked resource
      properties:
        idref:
          type: string
          description: id reference to the resource
        resourceSlots:
          $ref: '#/components/schemas/resourseSlotDetail'
        dateOfBooking:
          type: string
          description: date of the booking
          format: date
      required:
        - idref
        - resourceSlots
        - dateOfBooking
    resourseSlotDetail:
      title: resourseSlotDetail
      x-stoplight:
        id: 7p9aek2uenlvl
      type: object
      description: |-
        a time slot which has a time interval span attached to the resource
        detail view of booking attached to the slot
      properties:
        id:
          type: string
          description: id of the slot
        useremail:
          type: string
          format: email
          description: useremail attached to this booking
        attime:
          type: string
          format: date-time
          description: |-
            Time when system register and accepts the booking made by the user
            This is usually after the user have performed the payment
        status:
          type: string
          description: status of the booking
        starttime:
          type: string
          description: Start time of the current slot
          format: time
        endtime:
          type: string
          format: time
          description: endtime of the slot
      required:
        - id
        - useremail
        - attime
        - status
        - starttime
        - endtime
    resourceSlotAdmin:
      title: resourceSlotAdmin
      x-stoplight:
        id: 1wa5n0r36tzjb
      x-tags:
        - booking
      type: object
      description: slot information made available for adminstrator to view and manage
      properties:
        slotdetail:
          $ref: '#/components/schemas/resourseSlotDetail'
        checkouttime:
          type: string
          format: date-time
          description: checkout time of the user
        leaseid:
          type: integer
          description: leasing session id associate with database
        paymentsessionid:
          type: string
          description: retrieval of paymentsessionid associate with the booking
      required:
        - slotdetail
        - checkouttime
        - leaseid
        - paymentsessionid
    errorMsg:
      title: errorMsg
      x-stoplight:
        id: 8f4xio340467i
      x-tags:
        - error
      type: object
      properties:
        code:
          type: integer
          description: server error code
        message:
          type: string
      required:
        - code
        - message
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: use authorization bearer
tags:
  - name: auth
  - name: booking
  - name: user
